# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Roald Joosen
description: I just want to see what happens...
keywords: Robot, DIY, Research, Development, Programming
baseurl: ""
url: "https://roaldjoosen.nl"
primary_color: 122639
secondary_color: FFCE00
social:
  - name: Github
    icon: fa-github
    url: https://github.com/robotjoosen
  - name: LinkedIn
    icon: fa-linkedin
    url: https://www.linkedin.com/in/roaldjoosen
  - name: YouTube
    icon: fa-youtube
    url: https://youtube.com/roaldjoosen

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /posts/:year-:month-:day/:title/
paginate: 5
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .idea
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - Makefile
  - docs/

